node() {
  stage('sample') {
   withCredentials([[$class: 'UsernamePassword', credentialsId: 'TERRAFORM-KEYS',
usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {

sh 'echo uname=$USERNAME pwd=$PASSWORD'
 }
  }
}
